array_width = 20
attr_fn_like_width = 30
blank_lines_lower_bound = 1
blank_lines_upper_bound = 2
chain_width = 20
combine_control_expr = false
empty_item_single_line = false
fn_params_layout = "Vertical"
fn_call_width = 20
force_multiline_blocks = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 60
generated_marker_line_search_limit = 500
format_macro_matchers = true
format_strings = true
imports_layout =  "Vertical"
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
max_width = 40
