array_width = 20
attr_fn_like_width = 30
blank_lines_lower_bound = 1
blank_lines_upper_bound = 2
chain_width = 20
combine_control_expr = false
empty_item_single_line = false
fn_params_layout = "Vertical"
fn_call_width = 20
force_multiline_blocks = true
format_code_in_doc_comments = true
